spring:
  config:
    import: optional:file:backend/.env[.properties]

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/finance_tracker}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope:
              - email
              - profile

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:}
      expiration: 86400000 # 24h in ms
      refresh-token:
        expiration: 604800000 # 7 days in ms

  frontend-url: ${FRONTEND_URL:http://localhost:5173} # For email links

server:
  port: ${SERVER_PORT:8089}
